version: '3.4'

volumes:
  db-data:

services:
  doit-api:
    image: zguesmi/doit-api:${API_VERSION}
    container_name: doit-api
    # entrypoint: "tail -f /dev/null"
    ports:
      - 8080:8080
    environment:
      - DB_HOST=doit-api-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - doit-api-db
      # doit-api-db:
      #   condition: service_healthy
    restart: on-failure

  doit-api-db:
    image: mysql:5
    container_name: doit-api-db
    # command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    # ports:
    #   - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    restart: always

  doit-api-db-ui:
    image: adminer:4.7.6
    container_name: doit-api-db-ui
    restart: always
    depends_on:
      - doit-api-db
      # doit-api-db:
      #   condition: service_healthy
    ports:
      - 8081:8080
