version: '3.4'

volumes:
  db-data:

services:
  doit-api:
    image: zguesmi/doit-api:0.0.1
    container_name: doit-api
    ports:
      - 80:8080
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mysql:5
    container_name: db
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    restart: always

  db-ui:
    image: adminer:4.7.6
    container_name: db-ui
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8081:8080
